### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by bakya236**

### CODE REVIEW

**Comment by bakya236** [comment]
Created a new issue [implement the dynamic forgot password page. #2](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/2) in GitHub

**Comment by bakya236** [comment]
Created a new issue [create place holder in the input field  #3](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/3) in GitHub

**Comment by bakya236** [comment]
Created a new issue [create place holder in the input field  #4](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/4) in GitHub

**Comment by bakya236** [comment]
Created a new issue [password pattern needed  #5](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/5) in GitHub

**Comment by bakya236** [comment]
Created a new issue [unwanted red color border for the input field  #6](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/6) in GitHub

**Comment by bakya236** [comment]
Created a new issue [pattern required for the full name inputfield #7](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/7) in GitHub

**Comment by bakya236** [comment]
Created a new issue [valiadate all the input fields #8](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/8) in GitHub

**Comment by bakya236** [comment]
Created a new issue [create default categories  #9](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/9) in GitHub

**Comment by bakya236** [comment]
Created a new issue [create default products #10](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/10) in GitHub

**Comment by bakya236** [comment]
Created a new issue [create password visibility by toggling in the password input field. #11](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/11) in GitHub

**Comment by Tamilselvan2747** [comment]
Created a new issue [Logout issue #12](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/12) in GitHub

**Comment by Tamilselvan2747** [comment]
Created a new issue [Image not showing #13](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/13) in GitHub

**Comment by Tamilselvan2747** [comment]
Created a new issue [Add to Bag Buttons Problem #14](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/14) in GitHub

**Comment by Tamilselvan2747** [comment]
Created a new issue [Product list not showing #15](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/15) in GitHub

**Comment by Tamilselvan2747** [comment]
Created a new issue [Make option for gender  #16](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/16) in GitHub

**Comment by Tamilselvan2747** [comment]
Created a new issue [Date Validation #17](https://github.com/fssa-batch3/bakyalakshmi.angappan__web_project/issues/17) in GitHub

**Pull request closed without merging**
